### ISSUE TITLE
Larger Link Text

### ISSUE THREAD

**Issue by Raysir** [jeroenrnl/zoph#60]
It is difficult to activate the [prev] and [next] links when using a hand held device (I-Pad). The link is so small, people click on the background instead of the active area. How can I make those links larger?

Ray

**Comment by jeroenrnl** [comment]
This should not be to complicated, I will look into this

**Comment by Raysir** [comment]
Great! It would be a big help to solve this problem.
Ray

**Comment by jeroenrnl** [comment]
In a future version, I will make Zoph "responsive", which will make Zoph automatically adapt it's interface to the screen size it is viewed on. Right now, this is a bridge too far, because I'm still in the middle of a transition to a template-based system. However, a simple workaround would be:

in `css.php` (depending on your Zoph version, this is either in the web root or in `templates\default`) you should find:
```
div.prev a, div.next a, div.pagelink a {
    text-decoration: none;
}
```
On my system it is on line 980, but this could vary by a few lines up and down, depending on your version.
If you add the following line: `padding: 20px;` (don't forget the ;) so it shows:
```
div.prev a, div.next a, div.pagelink a {
    text-decoration: none;
    padding: 20px;
}
```
You will add a 20 pixel border to the next and previous links (of course you can change 20px to any other value to your liking)

I am not marking this as closed as I have not made any changes to the Zoph code yet (this means that you will have to make this change again when upgrading Zoph!)

**Comment by jeroenrnl** [comment]
BTW: sorry for the delay, for some reason my mail system decided that the message from git that a new bug had been created was spam :disappointed:

**Comment by Raysir** [comment]
Thanks for your suggestion. I was able to make the change. It certainly increased the target area arround the [prev] and [next] links however it also changed the spacing of the page numbers at the bottom of the photos when you are in the [up] mode. By this I am saying that when I get into the mode of viewing a group of thumbnails there is a list of page numbers at the bottom. This list of page numbers is so distorted with this fix that I really cannot opperate in that mode. Is there a way to produce the enlarged target only arround the [prev] and [next] that one sees when moving from one window sized photo (the view that also includes things like title, location, date, time, ...)?

Thanks 
Ray

**Comment by jeroenrnl** [comment]
Yes, this is possible, by excluding the `div.pagelink a` from the definition:
````
div.prev a, div.next a {
    text-decoration: none;
    padding: 20px;
}

div.pagelink a {
    text-decoration: none;
}
```

Please leave this issue open, as I have not changed anything in the Zoph code...

**Comment by Raysir** [comment]
Great! That fixed the problem. Now it is quite usable even from small touch screens.
Thanks,
Ray

**Comment by jeroenrnl** [comment]
Changed how pagelinks look, should be much easier on touchscreens (and it looks better too, IMHO)
![pagelinks](https://cloud.githubusercontent.com/assets/1951972/13382104/ac157546-de6c-11e5-954f-3e58fbda684d.png)
